# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Abhi Bavishi
email: hello@abhibavishi.com
description: >
  The journey is the reward ðŸ¼
logo: "/assets/images/logo.png"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.abhibavishi.com" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Abhi Bavishi'
bio: >
  Growth Hacker. Writer. Entrepreneur.
  Curious about life. Ambitious about startups.
author_image: "/assets/images/author.jpg"
twitter_username: bavishiabhi
github_username:  abhibavishi

# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
